#+TITLE:       The Difficulties and Innovations of Early Video Games
#+AUTHOR:      Conrad Bailey
#+DESCRIPTION: Response to Reading 01 https://www3.nd.edu/~pbui/teaching/cse.40850.sp18/reading01.html

The earliest video games were designed to push their platforms'
capabilities as far as possible. Their purpose was to demonstrate the
power of the hardware, to impress their audience. This is inline with
the hardware-centric perspective that pervaded the computing industry
of that era. The nature of the beast limited the development
opportunity to only a certain type of person: engineers. This is
reflected in the nature of the games they made: /Spacewar/, a
glorified physics demonstration.

Spacewar was a game made by and for engineers, steeped in science
fiction and only a year after Alan Shepard entered low orbit. But the
creators unknowingly seized a crucial opportunity; they'd crafted a
narrative. They explained away the torpedoe's lack of gravitational
influence with photons. They explained that the hyperspace engines had
been rushed to production and presented risk with each use. This game
wasn't simply a stress test for the PDP-1, it had context,
humanity. It also struck up the long time love affair of space and
video games. Perhaps it's just that gamers and space lovers have a
large intersection, or the coincidence of the early days of video
games and the space race. But I like to think that it's just human
nature, staring into the blackness of a blank video screen, to imagine
outer space. In what other context does man stare into the void? To
have this first opportunity to mark man's place among the stars in a
completely new way, a landmark installment in a budding art form, and
wrap it up in a meaningless war. This is an early look into the way
video games would make humanity introspect in completely new and
sometimes jarring ways.

Nolan Bushnell and Ralph Baer took the next great challenge on:
introducing the layman to the engineers' pet project. Bushnell's
experiment with /Computer Space/ proved general audiences would
require a gentler introduction to video games; they didn't even have
the vocabulary to describe the thing, much less participate in
space-borne warfare. Baer's /Magnavox Odyssey/ was even farther ahead
of it's time; people weren't comfortable with the concept of
television games, much less where they fit in in the home. So to meet
the challenge the video game was distilled to almost the bare
essentials, /Pong!/.

One ball, two paddles, two counters, one color. It's next to
impossible to imagine a simpler game, and the brilliance of that is
two-fold. Psychologically, if people couldn't wrap their heads around
/Pong!/, there was not much hope for much else. Technologically, the
simplicity should minimize costs. It was a great recipe for wildfire.

It's fascinating how quickly the technology behind video games
splintered; in quick succession there had been one-off machines built
for custom logic, software widely distributed and modified,
mass-produced arcade machines, and early home console systems. Most
impressive to me is the introduction of the home console; Baer was
practically two steps ahead of the curve having bypassed the arcade
machine. It's a visionary idea to reach into the television and
control it yourself. It must have been an absolutely foreign concept
in it's day so you can hardly blame customers for thinking it a sales
gimmick.
